# Generated by Django 3.2.3 on 2021-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('importance', models.SmallIntegerField(choices=[('Very high', 0), ('high', 1), ('Normal', 2), ('Least ', 3)], default=0)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'todo',
                'ordering': ['-pub_date'],
            },
        ),
    ]
